### ISSUE TITLE
Converting txt to .hic

### ISSUE THREAD

**Issue by Oksanak22** [zsq-berry/3D-genome-tools#2]
Thank you for the script, but I have some issues with converting homer.txt.gz to .hic.
I tried to run 
java -Xmx4g -jar juicer_tools.jar pre -r 20000 -d /home/juicebox/GSM_20000_homer.txt.gz Lib2.hic Tb.fasta and it gave me an error:

java.io.IOException: Unexpected column count.  Check file format
        at juicebox.tools.utils.original.AsciiPairIterator.advance(AsciiPairIterator.java:148)
        at juicebox.tools.utils.original.AsciiPairIterator.<init>(AsciiPairIterator.java:72)
        at juicebox.tools.utils.original.Preprocessor.computeWholeGenomeMatrix(Preprocessor.java:555)
        at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:669)
        at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:419)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:122)
        at juicebox.tools.HiCTools.main(HiCTools.java:94)
java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.
        at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.mergeAndWriteBlocks(Preprocessor.java:1772)
        at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.access$000(Preprocessor.java:1541)
        at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:954)
        at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:671)
        at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:419)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:122)
        at juicebox.tools.HiCTools.main(HiCTools.java:94)

Actually, I am able to open GSM_20000_homer.txt with Treeview but I need to have a .hic file for downstream analysis

Could you, please help me with that?

Thank you.

**Comment by sakusankun** [comment]
I met the same problem, have you solved this?
